version: "3"
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: main
    env_file: .env
    command: npm run start:dev
    ports:
      - $LOCALHOST_PORT:$LOCALHOST_PORT
    volumes:
      - .:/usr/app
      - /usr/app/node_modules 
    depends_on:
      - db_pgsql
    restart: unless-stopped

  db_pgsql:
    image: postgres:13.5
    container_name: pgsql
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PG_DATA: "/var/lib/postgres/data/"
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - pgdata:/var/lib/postgres/data
    restart: unless-stopped    

volumes:
  pgdata: